name: Refresh SportyBet Token

on:
  schedule:
    - cron: '*/25 * * * *'
  workflow_dispatch:

# CRITICAL FIX: Give the workflow permission to write to the repo
permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run Scraper
        run: node scrape-token.js

      - name: Commit new token
        env:
          # Pull the secret token you just created
          PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "Akanji Mus'ab"
          git config --global user.email "akanjimusab@gmail.com"
          git add token.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated token"
          
          # Force git to use the Secret Token to authenticate
          git remote set-url origin https://x-access-token:${PAT}@github.com/Brave290/OTP-agent.git
          git push
